.TH "soya_editor" "1" "0.4.2" "Jiba (Lamy Jean-Baptiste)" ""
.SH "NAME"
.LP 
soya_editor \- small 3D editor for soya
.SH "SYNTAX"
.LP 
soya_editor [<\fIfiles...\fP>]
.SH "DESCRIPTION"
.LP 
The Soya's 3D editor. It can be used to view Soya's materials, shape or world, or to create new materials, shape or world. The editor can also be extended to provide a level editor for a game.
.br 
Soya editor relies on EditObj.
.SH "FILES"
.LP 
\fI~/.soya_editor\fP 
.SH "AUTHORS"
.LP 
Jiba (Lamy Jean\-Baptiste) <jiba@tuxfamily.org>
