# -*- indent-tabs-mode: t -*-

HAVE_OPENGL = 1
OPENGL_INCDIR = ''
OPENGL_LIB = 'GL'
OPENGL_LIBDIR = ''

HAVE_SDL = 1
SDL_INCDIR = ''
SDL_LIB = 'SDL'
SDL_LIBDIR = ''

HAVE_FREETYPE2 = 1
FREETYPE2_INCDIR = ''
FREETYPE2_LIB = 'freetype'
FREETYPE2_LIBDIR = ''

HAVE_CAL3D = 1
CAL3D_INCDIR = ''
CAL3D_LIB = 'cal3d'
CAL3D_LIBDIR = ''
