# -*- indent-tabs-mode: t -*-

# Soya 3D
# Copyright (C) 2003-2004 Jean-Baptiste LAMY -- jiba@tuxfamily.org
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Import C lib
include "c.pxd"
include "python.pxd"

cimport c_opengl
from c_opengl cimport GLenum, GLuint

GL_FALSE = c_opengl.GL_FALSE
GL_TRUE = c_opengl.GL_TRUE
GL_BYTE = c_opengl.GL_BYTE
GL_UNSIGNED_BYTE = c_opengl.GL_UNSIGNED_BYTE
GL_SHORT = c_opengl.GL_SHORT
GL_UNSIGNED_SHORT = c_opengl.GL_UNSIGNED_SHORT
GL_INT = c_opengl.GL_INT
GL_UNSIGNED_INT = c_opengl.GL_UNSIGNED_INT
GL_FLOAT = c_opengl.GL_FLOAT
GL_DOUBLE = c_opengl.GL_DOUBLE
GL_2_BYTES = c_opengl.GL_2_BYTES
GL_3_BYTES = c_opengl.GL_3_BYTES
GL_4_BYTES = c_opengl.GL_4_BYTES
GL_POINTS = c_opengl.GL_POINTS
GL_LINES = c_opengl.GL_LINES
GL_LINE_LOOP = c_opengl.GL_LINE_LOOP
GL_LINE_STRIP = c_opengl.GL_LINE_STRIP
GL_TRIANGLES = c_opengl.GL_TRIANGLES
GL_TRIANGLE_STRIP = c_opengl.GL_TRIANGLE_STRIP
GL_TRIANGLE_FAN = c_opengl.GL_TRIANGLE_FAN
GL_QUADS = c_opengl.GL_QUADS
GL_QUAD_STRIP = c_opengl.GL_QUAD_STRIP
GL_POLYGON = c_opengl.GL_POLYGON
GL_VERTEX_ARRAY = c_opengl.GL_VERTEX_ARRAY
GL_NORMAL_ARRAY = c_opengl.GL_NORMAL_ARRAY
GL_COLOR_ARRAY = c_opengl.GL_COLOR_ARRAY
GL_INDEX_ARRAY = c_opengl.GL_INDEX_ARRAY
GL_TEXTURE_COORD_ARRAY = c_opengl.GL_TEXTURE_COORD_ARRAY
GL_EDGE_FLAG_ARRAY = c_opengl.GL_EDGE_FLAG_ARRAY
GL_VERTEX_ARRAY_SIZE = c_opengl.GL_VERTEX_ARRAY_SIZE
GL_VERTEX_ARRAY_TYPE = c_opengl.GL_VERTEX_ARRAY_TYPE
GL_VERTEX_ARRAY_STRIDE = c_opengl.GL_VERTEX_ARRAY_STRIDE
GL_NORMAL_ARRAY_TYPE = c_opengl.GL_NORMAL_ARRAY_TYPE
GL_NORMAL_ARRAY_STRIDE = c_opengl.GL_NORMAL_ARRAY_STRIDE
GL_COLOR_ARRAY_SIZE = c_opengl.GL_COLOR_ARRAY_SIZE
GL_COLOR_ARRAY_TYPE = c_opengl.GL_COLOR_ARRAY_TYPE
GL_COLOR_ARRAY_STRIDE = c_opengl.GL_COLOR_ARRAY_STRIDE
GL_INDEX_ARRAY_TYPE = c_opengl.GL_INDEX_ARRAY_TYPE
GL_INDEX_ARRAY_STRIDE = c_opengl.GL_INDEX_ARRAY_STRIDE
GL_TEXTURE_COORD_ARRAY_SIZE = c_opengl.GL_TEXTURE_COORD_ARRAY_SIZE
GL_TEXTURE_COORD_ARRAY_TYPE = c_opengl.GL_TEXTURE_COORD_ARRAY_TYPE
GL_TEXTURE_COORD_ARRAY_STRIDE = c_opengl.GL_TEXTURE_COORD_ARRAY_STRIDE
GL_EDGE_FLAG_ARRAY_STRIDE = c_opengl.GL_EDGE_FLAG_ARRAY_STRIDE
GL_VERTEX_ARRAY_POINTER = c_opengl.GL_VERTEX_ARRAY_POINTER
GL_NORMAL_ARRAY_POINTER = c_opengl.GL_NORMAL_ARRAY_POINTER
GL_COLOR_ARRAY_POINTER = c_opengl.GL_COLOR_ARRAY_POINTER
GL_INDEX_ARRAY_POINTER = c_opengl.GL_INDEX_ARRAY_POINTER
GL_TEXTURE_COORD_ARRAY_POINTER = c_opengl.GL_TEXTURE_COORD_ARRAY_POINTER
GL_EDGE_FLAG_ARRAY_POINTER = c_opengl.GL_EDGE_FLAG_ARRAY_POINTER
GL_V2F = c_opengl.GL_V2F
GL_V3F = c_opengl.GL_V3F
GL_C4UB_V2F = c_opengl.GL_C4UB_V2F
GL_C4UB_V3F = c_opengl.GL_C4UB_V3F
GL_C3F_V3F = c_opengl.GL_C3F_V3F
GL_N3F_V3F = c_opengl.GL_N3F_V3F
GL_C4F_N3F_V3F = c_opengl.GL_C4F_N3F_V3F
GL_T2F_V3F = c_opengl.GL_T2F_V3F
GL_T4F_V4F = c_opengl.GL_T4F_V4F
GL_T2F_C4UB_V3F = c_opengl.GL_T2F_C4UB_V3F
GL_T2F_C3F_V3F = c_opengl.GL_T2F_C3F_V3F
GL_T2F_N3F_V3F = c_opengl.GL_T2F_N3F_V3F
GL_T2F_C4F_N3F_V3F = c_opengl.GL_T2F_C4F_N3F_V3F
GL_T4F_C4F_N3F_V4F = c_opengl.GL_T4F_C4F_N3F_V4F
GL_MATRIX_MODE = c_opengl.GL_MATRIX_MODE
GL_MODELVIEW = c_opengl.GL_MODELVIEW
GL_PROJECTION = c_opengl.GL_PROJECTION
GL_TEXTURE = c_opengl.GL_TEXTURE
GL_POINT_SMOOTH = c_opengl.GL_POINT_SMOOTH
GL_POINT_SIZE = c_opengl.GL_POINT_SIZE
GL_POINT_SIZE_GRANULARITY = c_opengl.GL_POINT_SIZE_GRANULARITY
GL_POINT_SIZE_RANGE = c_opengl.GL_POINT_SIZE_RANGE
GL_LINE_SMOOTH = c_opengl.GL_LINE_SMOOTH
GL_LINE_STIPPLE = c_opengl.GL_LINE_STIPPLE
GL_LINE_STIPPLE_PATTERN = c_opengl.GL_LINE_STIPPLE_PATTERN
GL_LINE_STIPPLE_REPEAT = c_opengl.GL_LINE_STIPPLE_REPEAT
GL_LINE_WIDTH = c_opengl.GL_LINE_WIDTH
GL_LINE_WIDTH_GRANULARITY = c_opengl.GL_LINE_WIDTH_GRANULARITY
GL_LINE_WIDTH_RANGE = c_opengl.GL_LINE_WIDTH_RANGE
GL_POINT = c_opengl.GL_POINT
GL_LINE = c_opengl.GL_LINE
GL_FILL = c_opengl.GL_FILL
GL_CW = c_opengl.GL_CW
GL_CCW = c_opengl.GL_CCW
GL_FRONT = c_opengl.GL_FRONT
GL_BACK = c_opengl.GL_BACK
GL_POLYGON_MODE = c_opengl.GL_POLYGON_MODE
GL_POLYGON_SMOOTH = c_opengl.GL_POLYGON_SMOOTH
GL_POLYGON_STIPPLE = c_opengl.GL_POLYGON_STIPPLE
GL_EDGE_FLAG = c_opengl.GL_EDGE_FLAG
GL_CULL_FACE = c_opengl.GL_CULL_FACE
GL_CULL_FACE_MODE = c_opengl.GL_CULL_FACE_MODE
GL_FRONT_FACE = c_opengl.GL_FRONT_FACE
GL_POLYGON_OFFSET_FACTOR = c_opengl.GL_POLYGON_OFFSET_FACTOR
GL_POLYGON_OFFSET_UNITS = c_opengl.GL_POLYGON_OFFSET_UNITS
GL_POLYGON_OFFSET_POINT = c_opengl.GL_POLYGON_OFFSET_POINT
GL_POLYGON_OFFSET_LINE = c_opengl.GL_POLYGON_OFFSET_LINE
GL_POLYGON_OFFSET_FILL = c_opengl.GL_POLYGON_OFFSET_FILL
GL_COMPILE = c_opengl.GL_COMPILE
GL_COMPILE_AND_EXECUTE = c_opengl.GL_COMPILE_AND_EXECUTE
GL_LIST_BASE = c_opengl.GL_LIST_BASE
GL_LIST_INDEX = c_opengl.GL_LIST_INDEX
GL_LIST_MODE = c_opengl.GL_LIST_MODE
GL_NEVER = c_opengl.GL_NEVER
GL_LESS = c_opengl.GL_LESS
GL_EQUAL = c_opengl.GL_EQUAL
GL_LEQUAL = c_opengl.GL_LEQUAL
GL_GREATER = c_opengl.GL_GREATER
GL_NOTEQUAL = c_opengl.GL_NOTEQUAL
GL_GEQUAL = c_opengl.GL_GEQUAL
GL_ALWAYS = c_opengl.GL_ALWAYS
GL_DEPTH_TEST = c_opengl.GL_DEPTH_TEST
GL_DEPTH_BITS = c_opengl.GL_DEPTH_BITS
GL_DEPTH_CLEAR_VALUE = c_opengl.GL_DEPTH_CLEAR_VALUE
GL_DEPTH_FUNC = c_opengl.GL_DEPTH_FUNC
GL_DEPTH_RANGE = c_opengl.GL_DEPTH_RANGE
GL_DEPTH_WRITEMASK = c_opengl.GL_DEPTH_WRITEMASK
GL_DEPTH_COMPONENT = c_opengl.GL_DEPTH_COMPONENT
GL_LIGHTING = c_opengl.GL_LIGHTING
GL_LIGHT0 = c_opengl.GL_LIGHT0
GL_LIGHT1 = c_opengl.GL_LIGHT1
GL_LIGHT2 = c_opengl.GL_LIGHT2
GL_LIGHT3 = c_opengl.GL_LIGHT3
GL_LIGHT4 = c_opengl.GL_LIGHT4
GL_LIGHT5 = c_opengl.GL_LIGHT5
GL_LIGHT6 = c_opengl.GL_LIGHT6
GL_LIGHT7 = c_opengl.GL_LIGHT7
GL_SPOT_EXPONENT = c_opengl.GL_SPOT_EXPONENT
GL_SPOT_CUTOFF = c_opengl.GL_SPOT_CUTOFF
GL_CONSTANT_ATTENUATION = c_opengl.GL_CONSTANT_ATTENUATION
GL_LINEAR_ATTENUATION = c_opengl.GL_LINEAR_ATTENUATION
GL_QUADRATIC_ATTENUATION = c_opengl.GL_QUADRATIC_ATTENUATION
GL_AMBIENT = c_opengl.GL_AMBIENT
GL_DIFFUSE = c_opengl.GL_DIFFUSE
GL_SPECULAR = c_opengl.GL_SPECULAR
GL_SHININESS = c_opengl.GL_SHININESS
GL_EMISSION = c_opengl.GL_EMISSION
GL_POSITION = c_opengl.GL_POSITION
GL_SPOT_DIRECTION = c_opengl.GL_SPOT_DIRECTION
GL_AMBIENT_AND_DIFFUSE = c_opengl.GL_AMBIENT_AND_DIFFUSE
GL_COLOR_INDEXES = c_opengl.GL_COLOR_INDEXES
GL_LIGHT_MODEL_TWO_SIDE = c_opengl.GL_LIGHT_MODEL_TWO_SIDE
GL_LIGHT_MODEL_LOCAL_VIEWER = c_opengl.GL_LIGHT_MODEL_LOCAL_VIEWER
GL_LIGHT_MODEL_AMBIENT = c_opengl.GL_LIGHT_MODEL_AMBIENT
GL_FRONT_AND_BACK = c_opengl.GL_FRONT_AND_BACK
GL_SHADE_MODEL = c_opengl.GL_SHADE_MODEL
GL_FLAT = c_opengl.GL_FLAT
GL_SMOOTH = c_opengl.GL_SMOOTH
GL_COLOR_MATERIAL = c_opengl.GL_COLOR_MATERIAL
GL_COLOR_MATERIAL_FACE = c_opengl.GL_COLOR_MATERIAL_FACE
GL_COLOR_MATERIAL_PARAMETER = c_opengl.GL_COLOR_MATERIAL_PARAMETER
GL_NORMALIZE = c_opengl.GL_NORMALIZE
GL_CLIP_PLANE0 = c_opengl.GL_CLIP_PLANE0
GL_CLIP_PLANE1 = c_opengl.GL_CLIP_PLANE1
GL_CLIP_PLANE2 = c_opengl.GL_CLIP_PLANE2
GL_CLIP_PLANE3 = c_opengl.GL_CLIP_PLANE3
GL_CLIP_PLANE4 = c_opengl.GL_CLIP_PLANE4
GL_CLIP_PLANE5 = c_opengl.GL_CLIP_PLANE5
GL_ACCUM_RED_BITS = c_opengl.GL_ACCUM_RED_BITS
GL_ACCUM_GREEN_BITS = c_opengl.GL_ACCUM_GREEN_BITS
GL_ACCUM_BLUE_BITS = c_opengl.GL_ACCUM_BLUE_BITS
GL_ACCUM_ALPHA_BITS = c_opengl.GL_ACCUM_ALPHA_BITS
GL_ACCUM_CLEAR_VALUE = c_opengl.GL_ACCUM_CLEAR_VALUE
GL_ACCUM = c_opengl.GL_ACCUM
GL_ADD = c_opengl.GL_ADD
GL_LOAD = c_opengl.GL_LOAD
GL_MULT = c_opengl.GL_MULT
GL_RETURN = c_opengl.GL_RETURN
GL_ALPHA_TEST = c_opengl.GL_ALPHA_TEST
GL_ALPHA_TEST_REF = c_opengl.GL_ALPHA_TEST_REF
GL_ALPHA_TEST_FUNC = c_opengl.GL_ALPHA_TEST_FUNC
GL_BLEND = c_opengl.GL_BLEND
GL_BLEND_SRC = c_opengl.GL_BLEND_SRC
GL_BLEND_DST = c_opengl.GL_BLEND_DST
GL_ZERO = c_opengl.GL_ZERO
GL_ONE = c_opengl.GL_ONE
GL_SRC_COLOR = c_opengl.GL_SRC_COLOR
GL_ONE_MINUS_SRC_COLOR = c_opengl.GL_ONE_MINUS_SRC_COLOR
GL_SRC_ALPHA = c_opengl.GL_SRC_ALPHA
GL_ONE_MINUS_SRC_ALPHA = c_opengl.GL_ONE_MINUS_SRC_ALPHA
GL_DST_ALPHA = c_opengl.GL_DST_ALPHA
GL_ONE_MINUS_DST_ALPHA = c_opengl.GL_ONE_MINUS_DST_ALPHA
GL_DST_COLOR = c_opengl.GL_DST_COLOR
GL_ONE_MINUS_DST_COLOR = c_opengl.GL_ONE_MINUS_DST_COLOR
GL_SRC_ALPHA_SATURATE = c_opengl.GL_SRC_ALPHA_SATURATE
GL_CONSTANT_COLOR = c_opengl.GL_CONSTANT_COLOR
GL_ONE_MINUS_CONSTANT_COLOR = c_opengl.GL_ONE_MINUS_CONSTANT_COLOR
GL_CONSTANT_ALPHA = c_opengl.GL_CONSTANT_ALPHA
GL_ONE_MINUS_CONSTANT_ALPHA = c_opengl.GL_ONE_MINUS_CONSTANT_ALPHA
GL_FEEDBACK = c_opengl.GL_FEEDBACK
GL_RENDER = c_opengl.GL_RENDER
GL_SELECT = c_opengl.GL_SELECT
GL_2D = c_opengl.GL_2D
GL_3D = c_opengl.GL_3D
GL_3D_COLOR = c_opengl.GL_3D_COLOR
GL_3D_COLOR_TEXTURE = c_opengl.GL_3D_COLOR_TEXTURE
GL_4D_COLOR_TEXTURE = c_opengl.GL_4D_COLOR_TEXTURE
GL_POINT_TOKEN = c_opengl.GL_POINT_TOKEN
GL_LINE_TOKEN = c_opengl.GL_LINE_TOKEN
GL_LINE_RESET_TOKEN = c_opengl.GL_LINE_RESET_TOKEN
GL_POLYGON_TOKEN = c_opengl.GL_POLYGON_TOKEN
GL_BITMAP_TOKEN = c_opengl.GL_BITMAP_TOKEN
GL_DRAW_PIXEL_TOKEN = c_opengl.GL_DRAW_PIXEL_TOKEN
GL_COPY_PIXEL_TOKEN = c_opengl.GL_COPY_PIXEL_TOKEN
GL_PASS_THROUGH_TOKEN = c_opengl.GL_PASS_THROUGH_TOKEN
GL_FEEDBACK_BUFFER_POINTER = c_opengl.GL_FEEDBACK_BUFFER_POINTER
GL_FEEDBACK_BUFFER_SIZE = c_opengl.GL_FEEDBACK_BUFFER_SIZE
GL_FEEDBACK_BUFFER_TYPE = c_opengl.GL_FEEDBACK_BUFFER_TYPE
GL_SELECTION_BUFFER_POINTER = c_opengl.GL_SELECTION_BUFFER_POINTER
GL_SELECTION_BUFFER_SIZE = c_opengl.GL_SELECTION_BUFFER_SIZE
GL_FOG = c_opengl.GL_FOG
GL_FOG_MODE = c_opengl.GL_FOG_MODE
GL_FOG_DENSITY = c_opengl.GL_FOG_DENSITY
GL_FOG_COLOR = c_opengl.GL_FOG_COLOR
GL_FOG_INDEX = c_opengl.GL_FOG_INDEX
GL_FOG_START = c_opengl.GL_FOG_START
GL_FOG_END = c_opengl.GL_FOG_END
GL_LINEAR = c_opengl.GL_LINEAR
GL_EXP = c_opengl.GL_EXP
GL_EXP2 = c_opengl.GL_EXP2
GL_LOGIC_OP = c_opengl.GL_LOGIC_OP
GL_INDEX_LOGIC_OP = c_opengl.GL_INDEX_LOGIC_OP
GL_COLOR_LOGIC_OP = c_opengl.GL_COLOR_LOGIC_OP
GL_LOGIC_OP_MODE = c_opengl.GL_LOGIC_OP_MODE
GL_CLEAR = c_opengl.GL_CLEAR
GL_SET = c_opengl.GL_SET
GL_COPY = c_opengl.GL_COPY
GL_COPY_INVERTED = c_opengl.GL_COPY_INVERTED
GL_NOOP = c_opengl.GL_NOOP
GL_INVERT = c_opengl.GL_INVERT
GL_AND = c_opengl.GL_AND
GL_NAND = c_opengl.GL_NAND
GL_OR = c_opengl.GL_OR
GL_NOR = c_opengl.GL_NOR
GL_XOR = c_opengl.GL_XOR
GL_EQUIV = c_opengl.GL_EQUIV
GL_AND_REVERSE = c_opengl.GL_AND_REVERSE
GL_AND_INVERTED = c_opengl.GL_AND_INVERTED
GL_OR_REVERSE = c_opengl.GL_OR_REVERSE
GL_OR_INVERTED = c_opengl.GL_OR_INVERTED
GL_STENCIL_TEST = c_opengl.GL_STENCIL_TEST
GL_STENCIL_WRITEMASK = c_opengl.GL_STENCIL_WRITEMASK
GL_STENCIL_BITS = c_opengl.GL_STENCIL_BITS
GL_STENCIL_FUNC = c_opengl.GL_STENCIL_FUNC
GL_STENCIL_VALUE_MASK = c_opengl.GL_STENCIL_VALUE_MASK
GL_STENCIL_REF = c_opengl.GL_STENCIL_REF
GL_STENCIL_FAIL = c_opengl.GL_STENCIL_FAIL
GL_STENCIL_PASS_DEPTH_PASS = c_opengl.GL_STENCIL_PASS_DEPTH_PASS
GL_STENCIL_PASS_DEPTH_FAIL = c_opengl.GL_STENCIL_PASS_DEPTH_FAIL
GL_STENCIL_CLEAR_VALUE = c_opengl.GL_STENCIL_CLEAR_VALUE
GL_STENCIL_INDEX = c_opengl.GL_STENCIL_INDEX
GL_KEEP = c_opengl.GL_KEEP
GL_REPLACE = c_opengl.GL_REPLACE
GL_INCR = c_opengl.GL_INCR
GL_DECR = c_opengl.GL_DECR
GL_NONE = c_opengl.GL_NONE
GL_LEFT = c_opengl.GL_LEFT
GL_RIGHT = c_opengl.GL_RIGHT
GL_FRONT_LEFT = c_opengl.GL_FRONT_LEFT
GL_FRONT_RIGHT = c_opengl.GL_FRONT_RIGHT
GL_BACK_LEFT = c_opengl.GL_BACK_LEFT
GL_BACK_RIGHT = c_opengl.GL_BACK_RIGHT
GL_AUX0 = c_opengl.GL_AUX0
GL_AUX1 = c_opengl.GL_AUX1
GL_AUX2 = c_opengl.GL_AUX2
GL_AUX3 = c_opengl.GL_AUX3
GL_COLOR_INDEX = c_opengl.GL_COLOR_INDEX
GL_RED = c_opengl.GL_RED
GL_GREEN = c_opengl.GL_GREEN
GL_BLUE = c_opengl.GL_BLUE
GL_ALPHA = c_opengl.GL_ALPHA
GL_LUMINANCE = c_opengl.GL_LUMINANCE
GL_LUMINANCE_ALPHA = c_opengl.GL_LUMINANCE_ALPHA
GL_ALPHA_BITS = c_opengl.GL_ALPHA_BITS
GL_RED_BITS = c_opengl.GL_RED_BITS
GL_GREEN_BITS = c_opengl.GL_GREEN_BITS
GL_BLUE_BITS = c_opengl.GL_BLUE_BITS
GL_INDEX_BITS = c_opengl.GL_INDEX_BITS
GL_SUBPIXEL_BITS = c_opengl.GL_SUBPIXEL_BITS
GL_AUX_BUFFERS = c_opengl.GL_AUX_BUFFERS
GL_READ_BUFFER = c_opengl.GL_READ_BUFFER
GL_DRAW_BUFFER = c_opengl.GL_DRAW_BUFFER
GL_DOUBLEBUFFER = c_opengl.GL_DOUBLEBUFFER
GL_STEREO = c_opengl.GL_STEREO
GL_BITMAP = c_opengl.GL_BITMAP
GL_COLOR = c_opengl.GL_COLOR
GL_DEPTH = c_opengl.GL_DEPTH
GL_STENCIL = c_opengl.GL_STENCIL
GL_DITHER = c_opengl.GL_DITHER
GL_RGB = c_opengl.GL_RGB
GL_RGBA = c_opengl.GL_RGBA
GL_MAX_LIST_NESTING = c_opengl.GL_MAX_LIST_NESTING
GL_MAX_ATTRIB_STACK_DEPTH = c_opengl.GL_MAX_ATTRIB_STACK_DEPTH
GL_MAX_MODELVIEW_STACK_DEPTH = c_opengl.GL_MAX_MODELVIEW_STACK_DEPTH
GL_MAX_NAME_STACK_DEPTH = c_opengl.GL_MAX_NAME_STACK_DEPTH
GL_MAX_PROJECTION_STACK_DEPTH = c_opengl.GL_MAX_PROJECTION_STACK_DEPTH
GL_MAX_TEXTURE_STACK_DEPTH = c_opengl.GL_MAX_TEXTURE_STACK_DEPTH
GL_MAX_EVAL_ORDER = c_opengl.GL_MAX_EVAL_ORDER
GL_MAX_LIGHTS = c_opengl.GL_MAX_LIGHTS
GL_MAX_CLIP_PLANES = c_opengl.GL_MAX_CLIP_PLANES
GL_MAX_TEXTURE_SIZE = c_opengl.GL_MAX_TEXTURE_SIZE
GL_MAX_PIXEL_MAP_TABLE = c_opengl.GL_MAX_PIXEL_MAP_TABLE
GL_MAX_VIEWPORT_DIMS = c_opengl.GL_MAX_VIEWPORT_DIMS
GL_MAX_CLIENT_ATTRIB_STACK_DEPTH = c_opengl.GL_MAX_CLIENT_ATTRIB_STACK_DEPTH
GL_ATTRIB_STACK_DEPTH = c_opengl.GL_ATTRIB_STACK_DEPTH
GL_CLIENT_ATTRIB_STACK_DEPTH = c_opengl.GL_CLIENT_ATTRIB_STACK_DEPTH
GL_COLOR_CLEAR_VALUE = c_opengl.GL_COLOR_CLEAR_VALUE
GL_COLOR_WRITEMASK = c_opengl.GL_COLOR_WRITEMASK
GL_CURRENT_INDEX = c_opengl.GL_CURRENT_INDEX
GL_CURRENT_COLOR = c_opengl.GL_CURRENT_COLOR
GL_CURRENT_NORMAL = c_opengl.GL_CURRENT_NORMAL
GL_CURRENT_RASTER_COLOR = c_opengl.GL_CURRENT_RASTER_COLOR
GL_CURRENT_RASTER_DISTANCE = c_opengl.GL_CURRENT_RASTER_DISTANCE
GL_CURRENT_RASTER_INDEX = c_opengl.GL_CURRENT_RASTER_INDEX
GL_CURRENT_RASTER_POSITION = c_opengl.GL_CURRENT_RASTER_POSITION
GL_CURRENT_RASTER_TEXTURE_COORDS = c_opengl.GL_CURRENT_RASTER_TEXTURE_COORDS
GL_CURRENT_RASTER_POSITION_VALID = c_opengl.GL_CURRENT_RASTER_POSITION_VALID
GL_CURRENT_TEXTURE_COORDS = c_opengl.GL_CURRENT_TEXTURE_COORDS
GL_INDEX_CLEAR_VALUE = c_opengl.GL_INDEX_CLEAR_VALUE
GL_INDEX_MODE = c_opengl.GL_INDEX_MODE
GL_INDEX_WRITEMASK = c_opengl.GL_INDEX_WRITEMASK
GL_MODELVIEW_MATRIX = c_opengl.GL_MODELVIEW_MATRIX
GL_MODELVIEW_STACK_DEPTH = c_opengl.GL_MODELVIEW_STACK_DEPTH
GL_NAME_STACK_DEPTH = c_opengl.GL_NAME_STACK_DEPTH
GL_PROJECTION_MATRIX = c_opengl.GL_PROJECTION_MATRIX
GL_PROJECTION_STACK_DEPTH = c_opengl.GL_PROJECTION_STACK_DEPTH
GL_RENDER_MODE = c_opengl.GL_RENDER_MODE
GL_RGBA_MODE = c_opengl.GL_RGBA_MODE
GL_TEXTURE_MATRIX = c_opengl.GL_TEXTURE_MATRIX
GL_TEXTURE_STACK_DEPTH = c_opengl.GL_TEXTURE_STACK_DEPTH
GL_VIEWPORT = c_opengl.GL_VIEWPORT
GL_AUTO_NORMAL = c_opengl.GL_AUTO_NORMAL
GL_MAP1_COLOR_4 = c_opengl.GL_MAP1_COLOR_4
GL_MAP1_GRID_DOMAIN = c_opengl.GL_MAP1_GRID_DOMAIN
GL_MAP1_GRID_SEGMENTS = c_opengl.GL_MAP1_GRID_SEGMENTS
GL_MAP1_INDEX = c_opengl.GL_MAP1_INDEX
GL_MAP1_NORMAL = c_opengl.GL_MAP1_NORMAL
GL_MAP1_TEXTURE_COORD_1 = c_opengl.GL_MAP1_TEXTURE_COORD_1
GL_MAP1_TEXTURE_COORD_2 = c_opengl.GL_MAP1_TEXTURE_COORD_2
GL_MAP1_TEXTURE_COORD_3 = c_opengl.GL_MAP1_TEXTURE_COORD_3
GL_MAP1_TEXTURE_COORD_4 = c_opengl.GL_MAP1_TEXTURE_COORD_4
GL_MAP1_VERTEX_3 = c_opengl.GL_MAP1_VERTEX_3
GL_MAP1_VERTEX_4 = c_opengl.GL_MAP1_VERTEX_4
GL_MAP2_COLOR_4 = c_opengl.GL_MAP2_COLOR_4
GL_MAP2_GRID_DOMAIN = c_opengl.GL_MAP2_GRID_DOMAIN
GL_MAP2_GRID_SEGMENTS = c_opengl.GL_MAP2_GRID_SEGMENTS
GL_MAP2_INDEX = c_opengl.GL_MAP2_INDEX
GL_MAP2_NORMAL = c_opengl.GL_MAP2_NORMAL
GL_MAP2_TEXTURE_COORD_1 = c_opengl.GL_MAP2_TEXTURE_COORD_1
GL_MAP2_TEXTURE_COORD_2 = c_opengl.GL_MAP2_TEXTURE_COORD_2
GL_MAP2_TEXTURE_COORD_3 = c_opengl.GL_MAP2_TEXTURE_COORD_3
GL_MAP2_TEXTURE_COORD_4 = c_opengl.GL_MAP2_TEXTURE_COORD_4
GL_MAP2_VERTEX_3 = c_opengl.GL_MAP2_VERTEX_3
GL_MAP2_VERTEX_4 = c_opengl.GL_MAP2_VERTEX_4
GL_COEFF = c_opengl.GL_COEFF
GL_DOMAIN = c_opengl.GL_DOMAIN
GL_ORDER = c_opengl.GL_ORDER
GL_FOG_HINT = c_opengl.GL_FOG_HINT
GL_LINE_SMOOTH_HINT = c_opengl.GL_LINE_SMOOTH_HINT
GL_PERSPECTIVE_CORRECTION_HINT = c_opengl.GL_PERSPECTIVE_CORRECTION_HINT
GL_POINT_SMOOTH_HINT = c_opengl.GL_POINT_SMOOTH_HINT
GL_POLYGON_SMOOTH_HINT = c_opengl.GL_POLYGON_SMOOTH_HINT
GL_DONT_CARE = c_opengl.GL_DONT_CARE
GL_FASTEST = c_opengl.GL_FASTEST
GL_NICEST = c_opengl.GL_NICEST
GL_SCISSOR_TEST = c_opengl.GL_SCISSOR_TEST
GL_SCISSOR_BOX = c_opengl.GL_SCISSOR_BOX
GL_MAP_COLOR = c_opengl.GL_MAP_COLOR
GL_MAP_STENCIL = c_opengl.GL_MAP_STENCIL
GL_INDEX_SHIFT = c_opengl.GL_INDEX_SHIFT
GL_INDEX_OFFSET = c_opengl.GL_INDEX_OFFSET
GL_RED_SCALE = c_opengl.GL_RED_SCALE
GL_RED_BIAS = c_opengl.GL_RED_BIAS
GL_GREEN_SCALE = c_opengl.GL_GREEN_SCALE
GL_GREEN_BIAS = c_opengl.GL_GREEN_BIAS
GL_BLUE_SCALE = c_opengl.GL_BLUE_SCALE
GL_BLUE_BIAS = c_opengl.GL_BLUE_BIAS
GL_ALPHA_SCALE = c_opengl.GL_ALPHA_SCALE
GL_ALPHA_BIAS = c_opengl.GL_ALPHA_BIAS
GL_DEPTH_SCALE = c_opengl.GL_DEPTH_SCALE
GL_DEPTH_BIAS = c_opengl.GL_DEPTH_BIAS
GL_PIXEL_MAP_S_TO_S_SIZE = c_opengl.GL_PIXEL_MAP_S_TO_S_SIZE
GL_PIXEL_MAP_I_TO_I_SIZE = c_opengl.GL_PIXEL_MAP_I_TO_I_SIZE
GL_PIXEL_MAP_I_TO_R_SIZE = c_opengl.GL_PIXEL_MAP_I_TO_R_SIZE
GL_PIXEL_MAP_I_TO_G_SIZE = c_opengl.GL_PIXEL_MAP_I_TO_G_SIZE
GL_PIXEL_MAP_I_TO_B_SIZE = c_opengl.GL_PIXEL_MAP_I_TO_B_SIZE
GL_PIXEL_MAP_I_TO_A_SIZE = c_opengl.GL_PIXEL_MAP_I_TO_A_SIZE
GL_PIXEL_MAP_R_TO_R_SIZE = c_opengl.GL_PIXEL_MAP_R_TO_R_SIZE
GL_PIXEL_MAP_G_TO_G_SIZE = c_opengl.GL_PIXEL_MAP_G_TO_G_SIZE
GL_PIXEL_MAP_B_TO_B_SIZE = c_opengl.GL_PIXEL_MAP_B_TO_B_SIZE
GL_PIXEL_MAP_A_TO_A_SIZE = c_opengl.GL_PIXEL_MAP_A_TO_A_SIZE
GL_PIXEL_MAP_S_TO_S = c_opengl.GL_PIXEL_MAP_S_TO_S
GL_PIXEL_MAP_I_TO_I = c_opengl.GL_PIXEL_MAP_I_TO_I
GL_PIXEL_MAP_I_TO_R = c_opengl.GL_PIXEL_MAP_I_TO_R
GL_PIXEL_MAP_I_TO_G = c_opengl.GL_PIXEL_MAP_I_TO_G
GL_PIXEL_MAP_I_TO_B = c_opengl.GL_PIXEL_MAP_I_TO_B
GL_PIXEL_MAP_I_TO_A = c_opengl.GL_PIXEL_MAP_I_TO_A
GL_PIXEL_MAP_R_TO_R = c_opengl.GL_PIXEL_MAP_R_TO_R
GL_PIXEL_MAP_G_TO_G = c_opengl.GL_PIXEL_MAP_G_TO_G
GL_PIXEL_MAP_B_TO_B = c_opengl.GL_PIXEL_MAP_B_TO_B
GL_PIXEL_MAP_A_TO_A = c_opengl.GL_PIXEL_MAP_A_TO_A
GL_PACK_ALIGNMENT = c_opengl.GL_PACK_ALIGNMENT
GL_PACK_LSB_FIRST = c_opengl.GL_PACK_LSB_FIRST
GL_PACK_ROW_LENGTH = c_opengl.GL_PACK_ROW_LENGTH
GL_PACK_SKIP_PIXELS = c_opengl.GL_PACK_SKIP_PIXELS
GL_PACK_SKIP_ROWS = c_opengl.GL_PACK_SKIP_ROWS
GL_PACK_SWAP_BYTES = c_opengl.GL_PACK_SWAP_BYTES
GL_UNPACK_ALIGNMENT = c_opengl.GL_UNPACK_ALIGNMENT
GL_UNPACK_LSB_FIRST = c_opengl.GL_UNPACK_LSB_FIRST
GL_UNPACK_ROW_LENGTH = c_opengl.GL_UNPACK_ROW_LENGTH
GL_UNPACK_SKIP_PIXELS = c_opengl.GL_UNPACK_SKIP_PIXELS
GL_UNPACK_SKIP_ROWS = c_opengl.GL_UNPACK_SKIP_ROWS
GL_UNPACK_SWAP_BYTES = c_opengl.GL_UNPACK_SWAP_BYTES
GL_ZOOM_X = c_opengl.GL_ZOOM_X
GL_ZOOM_Y = c_opengl.GL_ZOOM_Y
GL_TEXTURE_ENV = c_opengl.GL_TEXTURE_ENV
GL_TEXTURE_ENV_MODE = c_opengl.GL_TEXTURE_ENV_MODE
GL_TEXTURE_1D = c_opengl.GL_TEXTURE_1D
GL_TEXTURE_2D = c_opengl.GL_TEXTURE_2D
GL_TEXTURE_WRAP_S = c_opengl.GL_TEXTURE_WRAP_S
GL_TEXTURE_WRAP_T = c_opengl.GL_TEXTURE_WRAP_T
GL_TEXTURE_MAG_FILTER = c_opengl.GL_TEXTURE_MAG_FILTER
GL_TEXTURE_MIN_FILTER = c_opengl.GL_TEXTURE_MIN_FILTER
GL_TEXTURE_ENV_COLOR = c_opengl.GL_TEXTURE_ENV_COLOR
GL_TEXTURE_GEN_S = c_opengl.GL_TEXTURE_GEN_S
GL_TEXTURE_GEN_T = c_opengl.GL_TEXTURE_GEN_T
GL_TEXTURE_GEN_MODE = c_opengl.GL_TEXTURE_GEN_MODE
GL_TEXTURE_BORDER_COLOR = c_opengl.GL_TEXTURE_BORDER_COLOR
GL_TEXTURE_WIDTH = c_opengl.GL_TEXTURE_WIDTH
GL_TEXTURE_HEIGHT = c_opengl.GL_TEXTURE_HEIGHT
GL_TEXTURE_BORDER = c_opengl.GL_TEXTURE_BORDER
GL_TEXTURE_COMPONENTS = c_opengl.GL_TEXTURE_COMPONENTS
GL_TEXTURE_RED_SIZE = c_opengl.GL_TEXTURE_RED_SIZE
GL_TEXTURE_GREEN_SIZE = c_opengl.GL_TEXTURE_GREEN_SIZE
GL_TEXTURE_BLUE_SIZE = c_opengl.GL_TEXTURE_BLUE_SIZE
GL_TEXTURE_ALPHA_SIZE = c_opengl.GL_TEXTURE_ALPHA_SIZE
GL_TEXTURE_LUMINANCE_SIZE = c_opengl.GL_TEXTURE_LUMINANCE_SIZE
GL_TEXTURE_INTENSITY_SIZE = c_opengl.GL_TEXTURE_INTENSITY_SIZE
GL_NEAREST_MIPMAP_NEAREST = c_opengl.GL_NEAREST_MIPMAP_NEAREST
GL_NEAREST_MIPMAP_LINEAR = c_opengl.GL_NEAREST_MIPMAP_LINEAR
GL_LINEAR_MIPMAP_NEAREST = c_opengl.GL_LINEAR_MIPMAP_NEAREST
GL_LINEAR_MIPMAP_LINEAR = c_opengl.GL_LINEAR_MIPMAP_LINEAR
GL_OBJECT_LINEAR = c_opengl.GL_OBJECT_LINEAR
GL_OBJECT_PLANE = c_opengl.GL_OBJECT_PLANE
GL_EYE_LINEAR = c_opengl.GL_EYE_LINEAR
GL_EYE_PLANE = c_opengl.GL_EYE_PLANE
GL_SPHERE_MAP = c_opengl.GL_SPHERE_MAP
GL_DECAL = c_opengl.GL_DECAL
GL_MODULATE = c_opengl.GL_MODULATE
GL_NEAREST = c_opengl.GL_NEAREST
GL_REPEAT = c_opengl.GL_REPEAT
GL_CLAMP = c_opengl.GL_CLAMP
GL_S = c_opengl.GL_S
GL_T = c_opengl.GL_T
GL_R = c_opengl.GL_R
GL_Q = c_opengl.GL_Q
GL_TEXTURE_GEN_R = c_opengl.GL_TEXTURE_GEN_R
GL_TEXTURE_GEN_Q = c_opengl.GL_TEXTURE_GEN_Q
GL_VENDOR = c_opengl.GL_VENDOR
GL_RENDERER = c_opengl.GL_RENDERER
GL_VERSION = c_opengl.GL_VERSION
GL_EXTENSIONS = c_opengl.GL_EXTENSIONS
GL_NO_ERROR = c_opengl.GL_NO_ERROR
GL_INVALID_VALUE = c_opengl.GL_INVALID_VALUE
GL_INVALID_ENUM = c_opengl.GL_INVALID_ENUM
GL_INVALID_OPERATION = c_opengl.GL_INVALID_OPERATION
GL_STACK_OVERFLOW = c_opengl.GL_STACK_OVERFLOW
GL_STACK_UNDERFLOW = c_opengl.GL_STACK_UNDERFLOW
GL_OUT_OF_MEMORY = c_opengl.GL_OUT_OF_MEMORY
GL_CURRENT_BIT = c_opengl.GL_CURRENT_BIT
GL_POINT_BIT = c_opengl.GL_POINT_BIT
GL_LINE_BIT = c_opengl.GL_LINE_BIT
GL_POLYGON_BIT = c_opengl.GL_POLYGON_BIT
GL_POLYGON_STIPPLE_BIT = c_opengl.GL_POLYGON_STIPPLE_BIT
GL_PIXEL_MODE_BIT = c_opengl.GL_PIXEL_MODE_BIT
GL_LIGHTING_BIT = c_opengl.GL_LIGHTING_BIT
GL_FOG_BIT = c_opengl.GL_FOG_BIT
GL_DEPTH_BUFFER_BIT = c_opengl.GL_DEPTH_BUFFER_BIT
GL_ACCUM_BUFFER_BIT = c_opengl.GL_ACCUM_BUFFER_BIT
GL_STENCIL_BUFFER_BIT = c_opengl.GL_STENCIL_BUFFER_BIT
GL_VIEWPORT_BIT = c_opengl.GL_VIEWPORT_BIT
GL_TRANSFORM_BIT = c_opengl.GL_TRANSFORM_BIT
GL_ENABLE_BIT = c_opengl.GL_ENABLE_BIT
GL_COLOR_BUFFER_BIT = c_opengl.GL_COLOR_BUFFER_BIT
GL_HINT_BIT = c_opengl.GL_HINT_BIT
GL_EVAL_BIT = c_opengl.GL_EVAL_BIT
GL_LIST_BIT = c_opengl.GL_LIST_BIT
GL_TEXTURE_BIT = c_opengl.GL_TEXTURE_BIT
GL_SCISSOR_BIT = c_opengl.GL_SCISSOR_BIT
GL_ALL_ATTRIB_BITS = c_opengl.GL_ALL_ATTRIB_BITS
GL_PROXY_TEXTURE_1D = c_opengl.GL_PROXY_TEXTURE_1D
GL_PROXY_TEXTURE_2D = c_opengl.GL_PROXY_TEXTURE_2D
GL_TEXTURE_PRIORITY = c_opengl.GL_TEXTURE_PRIORITY
GL_TEXTURE_RESIDENT = c_opengl.GL_TEXTURE_RESIDENT
GL_TEXTURE_BINDING_1D = c_opengl.GL_TEXTURE_BINDING_1D
GL_TEXTURE_BINDING_2D = c_opengl.GL_TEXTURE_BINDING_2D
GL_TEXTURE_INTERNAL_FORMAT = c_opengl.GL_TEXTURE_INTERNAL_FORMAT
GL_ALPHA4 = c_opengl.GL_ALPHA4
GL_ALPHA8 = c_opengl.GL_ALPHA8
GL_ALPHA12 = c_opengl.GL_ALPHA12
GL_ALPHA16 = c_opengl.GL_ALPHA16
GL_LUMINANCE4 = c_opengl.GL_LUMINANCE4
GL_LUMINANCE8 = c_opengl.GL_LUMINANCE8
GL_LUMINANCE12 = c_opengl.GL_LUMINANCE12
GL_LUMINANCE16 = c_opengl.GL_LUMINANCE16
GL_LUMINANCE4_ALPHA4 = c_opengl.GL_LUMINANCE4_ALPHA4
GL_LUMINANCE6_ALPHA2 = c_opengl.GL_LUMINANCE6_ALPHA2
GL_LUMINANCE8_ALPHA8 = c_opengl.GL_LUMINANCE8_ALPHA8
GL_LUMINANCE12_ALPHA4 = c_opengl.GL_LUMINANCE12_ALPHA4
GL_LUMINANCE12_ALPHA12 = c_opengl.GL_LUMINANCE12_ALPHA12
GL_LUMINANCE16_ALPHA16 = c_opengl.GL_LUMINANCE16_ALPHA16
GL_INTENSITY = c_opengl.GL_INTENSITY
GL_INTENSITY4 = c_opengl.GL_INTENSITY4
GL_INTENSITY8 = c_opengl.GL_INTENSITY8
GL_INTENSITY12 = c_opengl.GL_INTENSITY12
GL_INTENSITY16 = c_opengl.GL_INTENSITY16
GL_R3_G3_B2 = c_opengl.GL_R3_G3_B2
GL_RGB4 = c_opengl.GL_RGB4
GL_RGB5 = c_opengl.GL_RGB5
GL_RGB8 = c_opengl.GL_RGB8
GL_RGB10 = c_opengl.GL_RGB10
GL_RGB12 = c_opengl.GL_RGB12
GL_RGB16 = c_opengl.GL_RGB16
GL_RGBA2 = c_opengl.GL_RGBA2
GL_RGBA4 = c_opengl.GL_RGBA4
GL_RGB5_A1 = c_opengl.GL_RGB5_A1
GL_RGBA8 = c_opengl.GL_RGBA8
GL_RGB10_A2 = c_opengl.GL_RGB10_A2
GL_RGBA12 = c_opengl.GL_RGBA12
GL_RGBA16 = c_opengl.GL_RGBA16
GL_CLIENT_PIXEL_STORE_BIT = c_opengl.GL_CLIENT_PIXEL_STORE_BIT
GL_CLIENT_VERTEX_ARRAY_BIT = c_opengl.GL_CLIENT_VERTEX_ARRAY_BIT
#GL_ALL_CLIENT_ATTRIB_BITS = c_opengl.GL_ALL_CLIENT_ATTRIB_BITS # This constant is missing in fucking nvidia gl.h file
GL_CLIENT_ALL_ATTRIB_BITS = c_opengl.GL_CLIENT_ALL_ATTRIB_BITS
GL_RESCALE_NORMAL = c_opengl.GL_RESCALE_NORMAL
GL_CLAMP_TO_EDGE = c_opengl.GL_CLAMP_TO_EDGE
GL_MAX_ELEMENTS_VERTICES = c_opengl.GL_MAX_ELEMENTS_VERTICES
GL_MAX_ELEMENTS_INDICES = c_opengl.GL_MAX_ELEMENTS_INDICES
GL_BGR = c_opengl.GL_BGR
GL_BGRA = c_opengl.GL_BGRA
GL_UNSIGNED_BYTE_3_3_2 = c_opengl.GL_UNSIGNED_BYTE_3_3_2
GL_UNSIGNED_BYTE_2_3_3_REV = c_opengl.GL_UNSIGNED_BYTE_2_3_3_REV
GL_UNSIGNED_SHORT_5_6_5 = c_opengl.GL_UNSIGNED_SHORT_5_6_5
GL_UNSIGNED_SHORT_5_6_5_REV = c_opengl.GL_UNSIGNED_SHORT_5_6_5_REV
GL_UNSIGNED_SHORT_4_4_4_4 = c_opengl.GL_UNSIGNED_SHORT_4_4_4_4
GL_UNSIGNED_SHORT_4_4_4_4_REV = c_opengl.GL_UNSIGNED_SHORT_4_4_4_4_REV
GL_UNSIGNED_SHORT_5_5_5_1 = c_opengl.GL_UNSIGNED_SHORT_5_5_5_1
GL_UNSIGNED_SHORT_1_5_5_5_REV = c_opengl.GL_UNSIGNED_SHORT_1_5_5_5_REV
GL_UNSIGNED_INT_8_8_8_8 = c_opengl.GL_UNSIGNED_INT_8_8_8_8
GL_UNSIGNED_INT_8_8_8_8_REV = c_opengl.GL_UNSIGNED_INT_8_8_8_8_REV
GL_UNSIGNED_INT_10_10_10_2 = c_opengl.GL_UNSIGNED_INT_10_10_10_2
GL_UNSIGNED_INT_2_10_10_10_REV = c_opengl.GL_UNSIGNED_INT_2_10_10_10_REV
GL_LIGHT_MODEL_COLOR_CONTROL = c_opengl.GL_LIGHT_MODEL_COLOR_CONTROL
GL_SINGLE_COLOR = c_opengl.GL_SINGLE_COLOR
GL_SEPARATE_SPECULAR_COLOR = c_opengl.GL_SEPARATE_SPECULAR_COLOR
GL_TEXTURE_MIN_LOD = c_opengl.GL_TEXTURE_MIN_LOD
GL_TEXTURE_MAX_LOD = c_opengl.GL_TEXTURE_MAX_LOD
GL_TEXTURE_BASE_LEVEL = c_opengl.GL_TEXTURE_BASE_LEVEL
GL_TEXTURE_MAX_LEVEL = c_opengl.GL_TEXTURE_MAX_LEVEL
GL_SMOOTH_POINT_SIZE_RANGE = c_opengl.GL_SMOOTH_POINT_SIZE_RANGE
GL_SMOOTH_POINT_SIZE_GRANULARITY = c_opengl.GL_SMOOTH_POINT_SIZE_GRANULARITY
GL_SMOOTH_LINE_WIDTH_RANGE = c_opengl.GL_SMOOTH_LINE_WIDTH_RANGE
GL_SMOOTH_LINE_WIDTH_GRANULARITY = c_opengl.GL_SMOOTH_LINE_WIDTH_GRANULARITY
GL_ALIASED_POINT_SIZE_RANGE = c_opengl.GL_ALIASED_POINT_SIZE_RANGE
GL_ALIASED_LINE_WIDTH_RANGE = c_opengl.GL_ALIASED_LINE_WIDTH_RANGE
GL_PACK_SKIP_IMAGES = c_opengl.GL_PACK_SKIP_IMAGES
GL_PACK_IMAGE_HEIGHT = c_opengl.GL_PACK_IMAGE_HEIGHT
GL_UNPACK_SKIP_IMAGES = c_opengl.GL_UNPACK_SKIP_IMAGES
GL_UNPACK_IMAGE_HEIGHT = c_opengl.GL_UNPACK_IMAGE_HEIGHT
GL_TEXTURE_3D = c_opengl.GL_TEXTURE_3D
GL_PROXY_TEXTURE_3D = c_opengl.GL_PROXY_TEXTURE_3D
GL_TEXTURE_DEPTH = c_opengl.GL_TEXTURE_DEPTH
GL_TEXTURE_WRAP_R = c_opengl.GL_TEXTURE_WRAP_R
GL_MAX_3D_TEXTURE_SIZE = c_opengl.GL_MAX_3D_TEXTURE_SIZE
GL_TEXTURE_BINDING_3D = c_opengl.GL_TEXTURE_BINDING_3D
GL_COLOR_TABLE = c_opengl.GL_COLOR_TABLE
GL_POST_CONVOLUTION_COLOR_TABLE = c_opengl.GL_POST_CONVOLUTION_COLOR_TABLE
GL_POST_COLOR_MATRIX_COLOR_TABLE = c_opengl.GL_POST_COLOR_MATRIX_COLOR_TABLE
GL_PROXY_COLOR_TABLE = c_opengl.GL_PROXY_COLOR_TABLE
GL_PROXY_POST_CONVOLUTION_COLOR_TABLE = c_opengl.GL_PROXY_POST_CONVOLUTION_COLOR_TABLE
GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE = c_opengl.GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE
GL_COLOR_TABLE_SCALE = c_opengl.GL_COLOR_TABLE_SCALE
GL_COLOR_TABLE_BIAS = c_opengl.GL_COLOR_TABLE_BIAS
GL_COLOR_TABLE_FORMAT = c_opengl.GL_COLOR_TABLE_FORMAT
GL_COLOR_TABLE_WIDTH = c_opengl.GL_COLOR_TABLE_WIDTH
GL_COLOR_TABLE_RED_SIZE = c_opengl.GL_COLOR_TABLE_RED_SIZE
GL_COLOR_TABLE_GREEN_SIZE = c_opengl.GL_COLOR_TABLE_GREEN_SIZE
GL_COLOR_TABLE_BLUE_SIZE = c_opengl.GL_COLOR_TABLE_BLUE_SIZE
GL_COLOR_TABLE_ALPHA_SIZE = c_opengl.GL_COLOR_TABLE_ALPHA_SIZE
GL_COLOR_TABLE_LUMINANCE_SIZE = c_opengl.GL_COLOR_TABLE_LUMINANCE_SIZE
GL_COLOR_TABLE_INTENSITY_SIZE = c_opengl.GL_COLOR_TABLE_INTENSITY_SIZE
GL_CONVOLUTION_1D = c_opengl.GL_CONVOLUTION_1D
GL_CONVOLUTION_2D = c_opengl.GL_CONVOLUTION_2D
GL_SEPARABLE_2D = c_opengl.GL_SEPARABLE_2D
GL_CONVOLUTION_BORDER_MODE = c_opengl.GL_CONVOLUTION_BORDER_MODE
GL_CONVOLUTION_FILTER_SCALE = c_opengl.GL_CONVOLUTION_FILTER_SCALE
GL_CONVOLUTION_FILTER_BIAS = c_opengl.GL_CONVOLUTION_FILTER_BIAS
GL_REDUCE = c_opengl.GL_REDUCE
GL_CONVOLUTION_FORMAT = c_opengl.GL_CONVOLUTION_FORMAT
GL_CONVOLUTION_WIDTH = c_opengl.GL_CONVOLUTION_WIDTH
GL_CONVOLUTION_HEIGHT = c_opengl.GL_CONVOLUTION_HEIGHT
GL_MAX_CONVOLUTION_WIDTH = c_opengl.GL_MAX_CONVOLUTION_WIDTH
GL_MAX_CONVOLUTION_HEIGHT = c_opengl.GL_MAX_CONVOLUTION_HEIGHT
GL_POST_CONVOLUTION_RED_SCALE = c_opengl.GL_POST_CONVOLUTION_RED_SCALE
GL_POST_CONVOLUTION_GREEN_SCALE = c_opengl.GL_POST_CONVOLUTION_GREEN_SCALE
GL_POST_CONVOLUTION_BLUE_SCALE = c_opengl.GL_POST_CONVOLUTION_BLUE_SCALE
GL_POST_CONVOLUTION_ALPHA_SCALE = c_opengl.GL_POST_CONVOLUTION_ALPHA_SCALE
GL_POST_CONVOLUTION_RED_BIAS = c_opengl.GL_POST_CONVOLUTION_RED_BIAS
GL_POST_CONVOLUTION_GREEN_BIAS = c_opengl.GL_POST_CONVOLUTION_GREEN_BIAS
GL_POST_CONVOLUTION_BLUE_BIAS = c_opengl.GL_POST_CONVOLUTION_BLUE_BIAS
GL_POST_CONVOLUTION_ALPHA_BIAS = c_opengl.GL_POST_CONVOLUTION_ALPHA_BIAS
GL_CONSTANT_BORDER = c_opengl.GL_CONSTANT_BORDER
GL_REPLICATE_BORDER = c_opengl.GL_REPLICATE_BORDER
GL_CONVOLUTION_BORDER_COLOR = c_opengl.GL_CONVOLUTION_BORDER_COLOR
GL_COLOR_MATRIX = c_opengl.GL_COLOR_MATRIX
GL_COLOR_MATRIX_STACK_DEPTH = c_opengl.GL_COLOR_MATRIX_STACK_DEPTH
GL_MAX_COLOR_MATRIX_STACK_DEPTH = c_opengl.GL_MAX_COLOR_MATRIX_STACK_DEPTH
GL_POST_COLOR_MATRIX_RED_SCALE = c_opengl.GL_POST_COLOR_MATRIX_RED_SCALE
GL_POST_COLOR_MATRIX_GREEN_SCALE = c_opengl.GL_POST_COLOR_MATRIX_GREEN_SCALE
GL_POST_COLOR_MATRIX_BLUE_SCALE = c_opengl.GL_POST_COLOR_MATRIX_BLUE_SCALE
GL_POST_COLOR_MATRIX_ALPHA_SCALE = c_opengl.GL_POST_COLOR_MATRIX_ALPHA_SCALE
GL_POST_COLOR_MATRIX_RED_BIAS = c_opengl.GL_POST_COLOR_MATRIX_RED_BIAS
GL_POST_COLOR_MATRIX_GREEN_BIAS = c_opengl.GL_POST_COLOR_MATRIX_GREEN_BIAS
GL_POST_COLOR_MATRIX_BLUE_BIAS = c_opengl.GL_POST_COLOR_MATRIX_BLUE_BIAS
GL_POST_COLOR_MATRIX_ALPHA_BIAS = c_opengl.GL_POST_COLOR_MATRIX_ALPHA_BIAS
GL_HISTOGRAM = c_opengl.GL_HISTOGRAM
GL_PROXY_HISTOGRAM = c_opengl.GL_PROXY_HISTOGRAM
GL_HISTOGRAM_WIDTH = c_opengl.GL_HISTOGRAM_WIDTH
GL_HISTOGRAM_FORMAT = c_opengl.GL_HISTOGRAM_FORMAT
GL_HISTOGRAM_RED_SIZE = c_opengl.GL_HISTOGRAM_RED_SIZE
GL_HISTOGRAM_GREEN_SIZE = c_opengl.GL_HISTOGRAM_GREEN_SIZE
GL_HISTOGRAM_BLUE_SIZE = c_opengl.GL_HISTOGRAM_BLUE_SIZE
GL_HISTOGRAM_ALPHA_SIZE = c_opengl.GL_HISTOGRAM_ALPHA_SIZE
GL_HISTOGRAM_LUMINANCE_SIZE = c_opengl.GL_HISTOGRAM_LUMINANCE_SIZE
GL_HISTOGRAM_SINK = c_opengl.GL_HISTOGRAM_SINK
GL_MINMAX = c_opengl.GL_MINMAX
GL_MINMAX_FORMAT = c_opengl.GL_MINMAX_FORMAT
GL_MINMAX_SINK = c_opengl.GL_MINMAX_SINK
GL_TABLE_TOO_LARGE = c_opengl.GL_TABLE_TOO_LARGE
GL_BLEND_EQUATION = c_opengl.GL_BLEND_EQUATION
GL_MIN = c_opengl.GL_MIN
GL_MAX = c_opengl.GL_MAX
GL_FUNC_ADD = c_opengl.GL_FUNC_ADD
GL_FUNC_SUBTRACT = c_opengl.GL_FUNC_SUBTRACT
GL_FUNC_REVERSE_SUBTRACT = c_opengl.GL_FUNC_REVERSE_SUBTRACT
GL_BLEND_COLOR = c_opengl.GL_BLEND_COLOR
GL_TEXTURE0 = c_opengl.GL_TEXTURE0
GL_TEXTURE1 = c_opengl.GL_TEXTURE1
GL_TEXTURE2 = c_opengl.GL_TEXTURE2
GL_TEXTURE3 = c_opengl.GL_TEXTURE3
GL_TEXTURE4 = c_opengl.GL_TEXTURE4
GL_TEXTURE5 = c_opengl.GL_TEXTURE5
GL_TEXTURE6 = c_opengl.GL_TEXTURE6
GL_TEXTURE7 = c_opengl.GL_TEXTURE7
GL_TEXTURE8 = c_opengl.GL_TEXTURE8
GL_TEXTURE9 = c_opengl.GL_TEXTURE9
GL_TEXTURE10 = c_opengl.GL_TEXTURE10
GL_TEXTURE11 = c_opengl.GL_TEXTURE11
GL_TEXTURE12 = c_opengl.GL_TEXTURE12
GL_TEXTURE13 = c_opengl.GL_TEXTURE13
GL_TEXTURE14 = c_opengl.GL_TEXTURE14
GL_TEXTURE15 = c_opengl.GL_TEXTURE15
GL_TEXTURE16 = c_opengl.GL_TEXTURE16
GL_TEXTURE17 = c_opengl.GL_TEXTURE17
GL_TEXTURE18 = c_opengl.GL_TEXTURE18
GL_TEXTURE19 = c_opengl.GL_TEXTURE19
GL_TEXTURE20 = c_opengl.GL_TEXTURE20
GL_TEXTURE21 = c_opengl.GL_TEXTURE21
GL_TEXTURE22 = c_opengl.GL_TEXTURE22
GL_TEXTURE23 = c_opengl.GL_TEXTURE23
GL_TEXTURE24 = c_opengl.GL_TEXTURE24
GL_TEXTURE25 = c_opengl.GL_TEXTURE25
GL_TEXTURE26 = c_opengl.GL_TEXTURE26
GL_TEXTURE27 = c_opengl.GL_TEXTURE27
GL_TEXTURE28 = c_opengl.GL_TEXTURE28
GL_TEXTURE29 = c_opengl.GL_TEXTURE29
GL_TEXTURE30 = c_opengl.GL_TEXTURE30
GL_TEXTURE31 = c_opengl.GL_TEXTURE31
GL_ACTIVE_TEXTURE = c_opengl.GL_ACTIVE_TEXTURE
GL_CLIENT_ACTIVE_TEXTURE = c_opengl.GL_CLIENT_ACTIVE_TEXTURE
GL_MAX_TEXTURE_UNITS = c_opengl.GL_MAX_TEXTURE_UNITS
GL_NORMAL_MAP = c_opengl.GL_NORMAL_MAP
GL_REFLECTION_MAP = c_opengl.GL_REFLECTION_MAP
GL_TEXTURE_CUBE_MAP = c_opengl.GL_TEXTURE_CUBE_MAP
GL_TEXTURE_BINDING_CUBE_MAP = c_opengl.GL_TEXTURE_BINDING_CUBE_MAP
GL_TEXTURE_CUBE_MAP_POSITIVE_X = c_opengl.GL_TEXTURE_CUBE_MAP_POSITIVE_X
GL_TEXTURE_CUBE_MAP_NEGATIVE_X = c_opengl.GL_TEXTURE_CUBE_MAP_NEGATIVE_X
GL_TEXTURE_CUBE_MAP_POSITIVE_Y = c_opengl.GL_TEXTURE_CUBE_MAP_POSITIVE_Y
GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = c_opengl.GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
GL_TEXTURE_CUBE_MAP_POSITIVE_Z = c_opengl.GL_TEXTURE_CUBE_MAP_POSITIVE_Z
GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = c_opengl.GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
GL_PROXY_TEXTURE_CUBE_MAP = c_opengl.GL_PROXY_TEXTURE_CUBE_MAP
GL_MAX_CUBE_MAP_TEXTURE_SIZE = c_opengl.GL_MAX_CUBE_MAP_TEXTURE_SIZE
GL_COMPRESSED_ALPHA = c_opengl.GL_COMPRESSED_ALPHA
GL_COMPRESSED_LUMINANCE = c_opengl.GL_COMPRESSED_LUMINANCE
GL_COMPRESSED_LUMINANCE_ALPHA = c_opengl.GL_COMPRESSED_LUMINANCE_ALPHA
GL_COMPRESSED_INTENSITY = c_opengl.GL_COMPRESSED_INTENSITY
GL_COMPRESSED_RGB = c_opengl.GL_COMPRESSED_RGB
GL_COMPRESSED_RGBA = c_opengl.GL_COMPRESSED_RGBA
GL_TEXTURE_COMPRESSION_HINT = c_opengl.GL_TEXTURE_COMPRESSION_HINT
GL_TEXTURE_COMPRESSED_IMAGE_SIZE = c_opengl.GL_TEXTURE_COMPRESSED_IMAGE_SIZE
GL_TEXTURE_COMPRESSED = c_opengl.GL_TEXTURE_COMPRESSED
GL_NUM_COMPRESSED_TEXTURE_FORMATS = c_opengl.GL_NUM_COMPRESSED_TEXTURE_FORMATS
GL_COMPRESSED_TEXTURE_FORMATS = c_opengl.GL_COMPRESSED_TEXTURE_FORMATS
GL_MULTISAMPLE = c_opengl.GL_MULTISAMPLE
GL_SAMPLE_ALPHA_TO_COVERAGE = c_opengl.GL_SAMPLE_ALPHA_TO_COVERAGE
GL_SAMPLE_ALPHA_TO_ONE = c_opengl.GL_SAMPLE_ALPHA_TO_ONE
GL_SAMPLE_COVERAGE = c_opengl.GL_SAMPLE_COVERAGE
GL_SAMPLE_BUFFERS = c_opengl.GL_SAMPLE_BUFFERS
GL_SAMPLES = c_opengl.GL_SAMPLES
GL_SAMPLE_COVERAGE_VALUE = c_opengl.GL_SAMPLE_COVERAGE_VALUE
GL_SAMPLE_COVERAGE_INVERT = c_opengl.GL_SAMPLE_COVERAGE_INVERT
GL_MULTISAMPLE_BIT = c_opengl.GL_MULTISAMPLE_BIT
GL_TRANSPOSE_MODELVIEW_MATRIX = c_opengl.GL_TRANSPOSE_MODELVIEW_MATRIX
GL_TRANSPOSE_PROJECTION_MATRIX = c_opengl.GL_TRANSPOSE_PROJECTION_MATRIX
GL_TRANSPOSE_TEXTURE_MATRIX = c_opengl.GL_TRANSPOSE_TEXTURE_MATRIX
GL_TRANSPOSE_COLOR_MATRIX = c_opengl.GL_TRANSPOSE_COLOR_MATRIX
GL_COMBINE = c_opengl.GL_COMBINE
GL_COMBINE_RGB = c_opengl.GL_COMBINE_RGB
GL_COMBINE_ALPHA = c_opengl.GL_COMBINE_ALPHA
GL_SOURCE0_RGB = c_opengl.GL_SOURCE0_RGB
GL_SOURCE1_RGB = c_opengl.GL_SOURCE1_RGB
GL_SOURCE2_RGB = c_opengl.GL_SOURCE2_RGB
GL_SOURCE0_ALPHA = c_opengl.GL_SOURCE0_ALPHA
GL_SOURCE1_ALPHA = c_opengl.GL_SOURCE1_ALPHA
GL_SOURCE2_ALPHA = c_opengl.GL_SOURCE2_ALPHA
GL_OPERAND0_RGB = c_opengl.GL_OPERAND0_RGB
GL_OPERAND1_RGB = c_opengl.GL_OPERAND1_RGB
GL_OPERAND2_RGB = c_opengl.GL_OPERAND2_RGB
GL_OPERAND0_ALPHA = c_opengl.GL_OPERAND0_ALPHA
GL_OPERAND1_ALPHA = c_opengl.GL_OPERAND1_ALPHA
GL_OPERAND2_ALPHA = c_opengl.GL_OPERAND2_ALPHA
GL_RGB_SCALE = c_opengl.GL_RGB_SCALE
GL_ADD_SIGNED = c_opengl.GL_ADD_SIGNED
GL_INTERPOLATE = c_opengl.GL_INTERPOLATE
GL_SUBTRACT = c_opengl.GL_SUBTRACT
GL_CONSTANT = c_opengl.GL_CONSTANT
GL_PRIMARY_COLOR = c_opengl.GL_PRIMARY_COLOR
GL_PREVIOUS = c_opengl.GL_PREVIOUS
GL_DOT3_RGB = c_opengl.GL_DOT3_RGB
GL_DOT3_RGBA = c_opengl.GL_DOT3_RGBA
GL_CLAMP_TO_BORDER = c_opengl.GL_CLAMP_TO_BORDER

def glClearColor(float arg1, float arg2, float arg3, float arg4):
	c_opengl.glClearColor(arg1, arg2, arg3, arg4)

def glPointSize(float arg):
	c_opengl.glPointSize(arg)
	
def glLineWidth(float arg):
	c_opengl.glLineWidth(arg)
	
def glEnable(int arg):
	c_opengl.glEnable(arg)
	
def glDisable(int arg):
	c_opengl.glDisable(arg)
	
def glLightModeli(int arg1, int arg2):
	c_opengl.glLightModeli(arg1, arg2)
		
def glBegin(int arg):
	c_opengl.glBegin(arg)
		
def glEnd():
	c_opengl.glEnd()
		
def glVertex2i(int x, int y):
	c_opengl.glVertex2i(x, y)
		
def glVertex2f(float x, float y):
	c_opengl.glVertex2f(x, y)
		
def glVertex3f(float x, float y, float z):
	c_opengl.glVertex3f(x, y, z)

def glNormal3f(float x, float y, float z):
	c_opengl.glNormal3f(x, y, z)

def glColor4f(float r, float g, float b, float a):
	c_opengl.glColor4f(r, g, b, a)

def glTexCoord2f(float u, float v):
	c_opengl.glTexCoord2f(u, v)

def glDeleteList(int id):
	c_opengl.glDeleteLists(id, 1)
	
def glGenList():
	return c_opengl.glGenLists(1)

def glGenLists(int nb):
	return c_opengl.glGenLists(nb)

def glNewList(int list_id, int mode = GL_COMPILE):
	c_opengl.glNewList(list_id, mode)

def glEndList():
	c_opengl.glEndList()

def glCallList(int list_id):
	c_opengl.glCallList(list_id)

def glRotatef(float angle,float x,float y,float z):
	c_opengl.glRotatef(angle,x,y,z)

def glPushMatrix():
	c_opengl.glPushMatrix()

def glPopMatrix():
	c_opengl.glPopMatrix()

def glTranslatef(float x,float y,float z):
	c_opengl.glTranslatef(x,y,z)

def glTranslated(float x,float y,float z):
	c_opengl.glTranslated(x,y,z)

def glScalef(float x,float y,float z):
	c_opengl.glScalef(x,y,z)

def glGenTextures(int n):
	cdef GLuint ret
	c_opengl.glGenTextures(n,&ret)
	return ret
 
def glBindTexture(int target, unsigned int texture):
	c_opengl.glBindTexture(target,texture)

def glPixelStorei(int pname, int param):
	c_opengl.glPixelStorei(pname,param)

def glLoadIdentity():
	c_opengl.glLoadIdentity()

def glAccum(int value, float coef):
	c_opengl.glAccum(value, coef)

def glMatrixMode(int mode):
	c_opengl.glMatrixMode(mode)
	
def glMultMatrix(GLenum mode):
	c_opengl.glMultMatrix(mode)
	
def glTexParameteri(int target, int param, int value):
	c_opengl.glTexParameteri(target, param, value)

def glPolygonOffset(float factor, float units):
	c_opengl.glPolygonOffset(factor, units)

def glOrtho(float x1, float x2, float y1, float y2, float z1, float z2):
	c_opengl.glOrtho(x1, x2, y1, y2, z1, z2)

def glPushAttrib(int arg):
	c_opengl.glPushAttrib(arg)

def glPopAttrib():
	c_opengl.glPopAttrib()
	
def glViewport(int x, int y, int width, int height):
	c_opengl.glViewport(x, y, width, height)

